services:
    pdf-watermarker:
        container_name: pdf-watermarker
        image: ghcr.io/meteyou/docker-pdf-watermarker:latest
        restart: unless-stopped
        ports:
          - "9021:9021"
